name: Deploy LS100

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    environment: ls100
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      
      - name: Install and build
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn workspace client build
      
      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp -r server deploy/
          cp -r client/dist deploy/client
          cp -r infra deploy/
          cp package.json deploy/
          cp yarn.lock deploy/
          rm -rf deploy/server/node_modules
          rm -rf deploy/server/tests
          tar -czf deployment.tar.gz -C deploy .
      
      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "deployment.tar.gz,infra/deploy/deploy.js"
          target: "/tmp/ls100-deploy"
      
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /tmp/ls100-deploy
            chmod +x infra/deploy/deploy.js
            if [ "${{ github.event_name }}" = "release" ]; then
              node infra/deploy/deploy.js production
            elif [ "${{ github.event.inputs.environment }}" = "production" ]; then
              node infra/deploy/deploy.js production
            else
              node infra/deploy/deploy.js staging
            fi